// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BootstrapController from "./bootstrap_controller"
application.register("bootstrap", BootstrapController)

import CardController from "./card_controller"
application.register("card", CardController)

import DocumentFilterController from "./document_filter_controller"
application.register("document-filter", DocumentFilterController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FloatingLabelController from "./floating_label_controller"
application.register("floating-label", FloatingLabelController)

import FullscreenController from "./fullscreen_controller"
application.register("fullscreen", FullscreenController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MobileController from "./mobile_controller"
application.register("mobile", MobileController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import PreloaderController from "./preloader_controller"
application.register("preloader", PreloaderController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SideNavController from "./side_nav_controller"
application.register("side-nav", SideNavController)

import TagsController from "./tags_controller"
application.register("tags", TagsController)

import TodoController from "./todo_controller"
application.register("todo", TodoController)


import AnimationController from "./animation_controller"
application.register("animation", AnimationController)


