require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/localities", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Locality. As you add validations to Locality, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Locality.create! valid_attributes
      get localities_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      locality = Locality.create! valid_attributes
      get locality_url(locality)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_locality_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      locality = Locality.create! valid_attributes
      get edit_locality_url(locality)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Locality" do
        expect {
          post localities_url, params: { locality: valid_attributes }
        }.to change(Locality, :count).by(1)
      end

      it "redirects to the created locality" do
        post localities_url, params: { locality: valid_attributes }
        expect(response).to redirect_to(locality_url(Locality.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Locality" do
        expect {
          post localities_url, params: { locality: invalid_attributes }
        }.to change(Locality, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post localities_url, params: { locality: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested locality" do
        locality = Locality.create! valid_attributes
        patch locality_url(locality), params: { locality: new_attributes }
        locality.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the locality" do
        locality = Locality.create! valid_attributes
        patch locality_url(locality), params: { locality: new_attributes }
        locality.reload
        expect(response).to redirect_to(locality_url(locality))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        locality = Locality.create! valid_attributes
        patch locality_url(locality), params: { locality: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested locality" do
      locality = Locality.create! valid_attributes
      expect {
        delete locality_url(locality)
      }.to change(Locality, :count).by(-1)
    end

    it "redirects to the localities list" do
      locality = Locality.create! valid_attributes
      delete locality_url(locality)
      expect(response).to redirect_to(localities_url)
    end
  end
end
